name: prueba2app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  image_picker: ^1.0.7
  
  flutter:
    sdk: flutter
  
  http: ^1.6.0
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.1
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  google_nav_bar: ^5.0.7
  emailjs: ^4.0.0
  connectivity_plus: ^6.1.0
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0
  uuid: ^4.5.2
  url_launcher: ^6.3.2
  firebase_storage: ^13.0.4
  record: ^5.1.0
  audioplayers: ^5.0.0
  permission_handler: ^11.0.0
  path_provider: ^2.0.0

dependency_overrides:
  record_linux: ^1.2.0
  record_platform_interface: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/profile_default.png
    - assets/logoazul.png
    - assets/logoblanco.png
    - assets/google_logo.png
    - assets/pruebahackaton-bfb64-cb3dbd690d75.json
    - assets/leoncibot.png
    - assets/leoncibotv2.png


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#hex_color" 
    theme_color: "#hex_color"
